// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvqkxcucqftfgjbcxebf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cWt4Y3VjcWZ0ZmdqYmN4ZWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDYyMDIsImV4cCI6MjA3MjIyMjIwMn0.CjVtTOyyyvc-4iTT5kSF4WPJgpnCTldSBZDdNd0Sfvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});